### ISSUE TITLE
Unable to build the app 

### ISSUE THREAD

**Issue by harshat5** [tito/experiment-tensorflow-lite#1]
RAN: /usr/bin/patch -t -d /content/experiment-tensorflow-lite/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/pyjnius-sdl2/armeabi-v7a__ndk_target_21/pyjnius -p1 -i /content/experiment-tensorflow-lite/.buildozer/android/platform/python-for-android/pythonforandroid/recipes/pyjnius/sdl2_jnienv_getter.patch

  STDOUT:
patching file jnius/jnius_jvm_android.pxi
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file jnius/jnius_jvm_android.pxi.rej
patching file jnius/env.py
Hunk #1 FAILED at 185.
1 out of 1 hunk FAILED -- saving rejects to file jnius/env.py.rej

I believe you used custom recipe for pyjnius. can you please share the recipe that was used to build the app or suggest the changes I need to make to get it working ?

Thanks

**Comment by RavenKape** [comment]
Same issue with mine

**Comment by tshirtman** [comment]
oh, that's probably because a new version of pyjnius has been released, try forcing pyjninus==1.4.0 (or maybe even 1.3.0) in the requirements of buildozer.spec.
